{
 "title": "PHM Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Horizontal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "phm_horizontal",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "phm_vertical",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HI Value",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "results_bearing1_1",
     "select": [
      [
       { "params": [ "HI value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Remaining Useful Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 9 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "measurement": "results_bearing1_1",
     "select": [
      [
       { "params": [ "RUL (Hours)" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "RUL Percentage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "measurement": "results_bearing1_1",
     "select": [
      [
       { "params": [ "RUL Percenatge" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}